### ISSUE TITLE
[FIX] Einheitlich Extensions NICHT in Methoden übergeben

### ISSUE THREAD

**Issue by LeichtMatrosee** [LeichtMatrosee/Sudoku#13]

**Comment by jannikglane** [comment]
pushed to jannik branch

**Comment by jannikglane** [comment]
Dateinamen werden ohne extension geladen. Und in allen save/load funktionen der FileHelper Klassen muss der Dateiname dementsprechend auch ohne extension übergeben werden.

**Comment by jannikglane** [comment]
halt stop

**Comment by jannikglane** [comment]
so jetzt aber, glaub ich
